version: 0.2

phases:
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://backend.yml

  build:
    commands:
      - DEPLOY_ENV="stage";
      - aws cloudformation deploy --template-file backend.yml --stack-name BaseInfraStack-$DEPLOY_ENV --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=$DEPLOY_ENV --no-fail-on-empty-changeset
      - aws cloudformation wait stack-create-complete --stack-name BaseInfraStack-$DEPLOY_ENV

  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name BaseInfraStack-$DEPLOY_ENV
